# Generated by Django 3.1.2 on 2021-07-03 13:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='subjectoffered',
            name='day',
        ),
        migrations.AddField(
            model_name='subjectoffered',
            name='dayofsub',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=220), blank=True, default=list, size=None),
        ),
    ]
