# Generated by Django 3.1.2 on 2021-07-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0002_auto_20210703_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=220)),
                ('extension', models.CharField(max_length=220)),
                ('service_offered', models.CharField(max_length=220)),
                ('description', models.CharField(max_length=220)),
            ],
        ),
    ]
