# Generated by Django 3.1.2 on 2021-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0003_counselorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorschedule',
            name='time',
            field=models.TimeField(),
        ),
    ]
