# Generated by Django 3.1.2 on 2021-07-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0005_auto_20210703_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselorschedule',
            name='extension',
        ),
    ]
