# Generated by Django 3.1.2 on 2021-07-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0006_remove_counselorschedule_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorschedule',
            name='service_offered',
            field=models.CharField(blank=True, choices=[('CLASS', 'CLASS'), ('COUNSELING', 'COUNSELING'), ('OTHERS', 'OTHERS')], max_length=220, null=True),
        ),
    ]
