# Generated by Django 3.1.2 on 2021-07-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0007_auto_20210703_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorschedule',
            name='description',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
