# Generated by Django 3.1.2 on 2021-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0009_auto_20210703_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectoffered',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='subjectoffered',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
