# Generated by Django 3.1.2 on 2021-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0010_auto_20210703_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselorschedule',
            name='time',
        ),
        migrations.AddField(
            model_name='counselorschedule',
            name='time1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counselorschedule',
            name='time2',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
