# Generated by Django 3.1.2 on 2021-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0011_auto_20210710_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorschedule',
            name='id',
            field=models.CharField(max_length=220, primary_key=True, serialize=False),
        ),
    ]
