# Generated by Django 3.1.2 on 2021-07-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0012_auto_20210710_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselorschedule',
            old_name='id',
            new_name='schedid',
        ),
    ]
