# Generated by Django 3.1.2 on 2021-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0013_auto_20210710_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersreferral',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachersreferral',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachersreferral',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
