# Generated by Django 3.1.2 on 2021-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0014_auto_20210712_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('schedid', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('time1', models.TimeField(blank=True, null=True)),
                ('time2', models.TimeField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, choices=[('CLASS', 'CLASS'), ('COUNSELING', 'COUNSELING'), ('OTHERS', 'OTHERS')], max_length=220, null=True)),
                ('description', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
    ]
