# Generated by Django 3.1.2 on 2021-07-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0015_studentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersreferral',
            name='status',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
