# Generated by Django 3.1.2 on 2021-07-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0017_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_user',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
