# Generated by Django 3.1.2 on 2021-07-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0018_auto_20210715_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
