# Generated by Django 3.1.2 on 2021-07-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0019_auto_20210715_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='holidaytime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
            ],
        ),
    ]
