# Generated by Django 3.1.2 on 2021-07-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0020_holidaytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_due_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='holidaytime',
        ),
    ]
