# Generated by Django 3.1.2 on 2021-07-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0021_auto_20210717_0005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
