# Generated by Django 3.1.2 on 2021-07-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0022_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('made_on', models.DateField()),
            ],
        ),
    ]
