# Generated by Django 3.1.2 on 2021-07-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0023_promise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateTimeField(help_text='date_of_birth', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Promise',
        ),
    ]
