# Generated by Django 3.1.2 on 2021-07-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0024_auto_20210717_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
