# Generated by Django 3.1.2 on 2021-07-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0025_delete_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studnumber', models.CharField(max_length=220)),
                ('subject_referred', models.CharField(max_length=220)),
                ('counselor', models.CharField(max_length=220)),
                ('employeeid', models.CharField(blank=True, max_length=220, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
    ]
