# Generated by Django 3.1.2 on 2021-08-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0026_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='year',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
