# Generated by Django 3.1.2 on 2021-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0027_auto_20210810_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='role',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
