# Generated by Django 3.1.2 on 2021-08-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0028_auto_20210810_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='firstname',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='lastname',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
