# Generated by Django 3.1.2 on 2021-08-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0029_auto_20210810_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='program_designation',
            field=models.CharField(blank=True, choices=[('BSIT', 'BSIT'), ('BSPT', 'BSPT'), ('BSMT', 'BSMT')], max_length=220, null=True),
        ),
    ]
