# Generated by Django 3.1.2 on 2021-08-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0030_auto_20210811_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
