# Generated by Django 3.1.2 on 2021-08-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0031_delete_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSchedule',
        ),
    ]
