# Generated by Django 3.1.2 on 2021-08-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0034_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('program_id', models.IntegerField(primary_key=True, serialize=False)),
                ('program_code', models.CharField(max_length=220)),
                ('program_name', models.CharField(max_length=220)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.schooloffices')),
            ],
        ),
    ]
