# Generated by Django 3.1.2 on 2021-08-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0035_degreeprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStudents',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('middlename', models.CharField(max_length=220)),
                ('year', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=220)),
                ('degree_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.degreeprogram')),
            ],
        ),
    ]
