# Generated by Django 3.1.2 on 2021-08-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0036_allstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstudents',
            name='year',
            field=models.IntegerField(),
        ),
    ]
