# Generated by Django 3.1.2 on 2021-08-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0037_auto_20210826_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstudents',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
