# Generated by Django 3.1.2 on 2021-08-26 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0039_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFaculty',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('middlename', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=220)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.department')),
            ],
        ),
    ]
