# Generated by Django 3.1.2 on 2021-08-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0040_allfaculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaculty',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
