# Generated by Django 3.1.2 on 2021-08-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0041_auto_20210826_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=220)),
            ],
        ),
    ]
