# Generated by Django 3.1.2 on 2021-08-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0043_auto_20210830_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='employeeid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
