# Generated by Django 3.1.2 on 2021-08-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0044_auto_20210830_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaculty',
            name='employee_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='allstudents',
            name='student_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='degreeprogram',
            name='program_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='employeeid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schooloffices',
            name='school_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='studnumber',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
