# Generated by Django 3.1.2 on 2021-08-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0045_auto_20210830_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='employeeid',
            new_name='employee_id',
        ),
    ]
