# Generated by Django 3.1.2 on 2021-08-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0046_auto_20210830_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=220)),
            ],
        ),
    ]
