# Generated by Django 3.1.2 on 2021-08-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0047_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='hasSetPassword',
            field=models.BooleanField(default=False),
        ),
    ]
