# Generated by Django 3.1.2 on 2021-08-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0049_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AccountCreated',
        ),
    ]
