# Generated by Django 3.1.2 on 2021-08-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0050_auto_20210830_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='hasSetPassword',
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='firstname',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='lastname',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
