# Generated by Django 3.1.2 on 2021-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0051_auto_20210830_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
