# Generated by Django 3.1.2 on 2021-08-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0052_accounts_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcreated',
            old_name='password',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='accountcreated',
            old_name='username',
            new_name='id_number',
        ),
    ]
