# Generated by Django 3.1.2 on 2021-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0053_auto_20210831_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreated',
            name='password',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
