# Generated by Django 3.1.2 on 2021-09-05 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0054_accountcreated_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCode',
            fields=[
                ('offer_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=220), default=list, size=None)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
