# Generated by Django 3.1.2 on 2021-09-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0055_offercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSubjects',
            fields=[
                ('subject_code', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('subject_title', models.CharField(max_length=220)),
                ('units', models.CharField(max_length=220)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.department')),
            ],
        ),
    ]
