# Generated by Django 3.1.2 on 2021-09-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0056_allsubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=225)),
            ],
        ),
    ]
