# Generated by Django 3.1.2 on 2021-09-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0057_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectWithSem',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('offer_code', models.CharField(max_length=225)),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.semester')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.allsubjects')),
            ],
        ),
    ]
