# Generated by Django 3.1.2 on 2021-09-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0059_newfacultyload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facultyload',
        ),
    ]
