# Generated by Django 3.1.2 on 2021-09-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0061_facultyload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facultyload',
        ),
    ]
