# Generated by Django 3.1.2 on 2021-09-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0064_auto_20210908_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfacultyload',
            name='id',
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
    ]
