# Generated by Django 3.1.2 on 2021-09-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0065_auto_20210908_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudentsload',
            fields=[
                ('id', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('offer_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counselling.offercode')),
                ('studnumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counselling.student')),
            ],
        ),
    ]
