# Generated by Django 3.1.2 on 2021-09-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0067_auto_20210908_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfacultyload',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.faculty', unique=True),
        ),
        migrations.AlterField(
            model_name='newfacultyload',
            name='offer_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='counselling.offercode', unique=True),
        ),
    ]
