# Generated by Django 3.1.2 on 2021-09-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0072_auto_20210910_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfacultyload',
            name='offer_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organization', serialize=False, to='counselling.offercode'),
        ),
    ]
