# Generated by Django 3.1.2 on 2021-09-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0073_auto_20210910_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstudents',
            old_name='degree_program_id',
            new_name='degree_program',
        ),
        migrations.RenameField(
            model_name='allstudents',
            old_name='student_id',
            new_name='studnumber',
        ),
    ]
