# Generated by Django 3.1.2 on 2021-09-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0074_auto_20210911_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstudents',
            old_name='degree_program',
            new_name='degree_program_id',
        ),
        migrations.RenameField(
            model_name='allstudents',
            old_name='studnumber',
            new_name='student_id',
        ),
    ]
