# Generated by Django 3.1.2 on 2021-09-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0076_auto_20210911_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referrals',
        ),
    ]
