# Generated by Django 3.1.2 on 2021-09-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0078_teachersreferral_behavior_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.CharField(max_length=220)),
                ('key2', models.CharField(max_length=220)),
                ('key3', models.CharField(max_length=220)),
            ],
            options={
                'unique_together': {('key1', 'key2', 'key3')},
            },
        ),
    ]
