# Generated by Django 3.1.2 on 2021-09-19 09:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0079_mytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOfferCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(default=None, max_length=225)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=220), default=list, size=None)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(default=None, max_length=225)),
                ('subject_code', models.CharField(default=None, max_length=225)),
                ('semd_id', models.CharField(default=None, max_length=225)),
                ('academic_year', models.CharField(default=None, max_length=225)),
            ],
            options={
                'unique_together': {('offer_code', 'semd_id', 'academic_year')},
            },
        ),
    ]
