# Generated by Django 3.1.2 on 2021-10-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0081_accountcreatedapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountCreatedApi',
        ),
    ]
