# Generated by Django 3.1.2 on 2021-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0082_delete_accountcreatedapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsApi',
            fields=[
                ('id_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=220)),
                ('code', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
    ]
