# Generated by Django 3.1.2 on 2021-10-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0083_accountsapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounselorSchedule',
        ),
    ]
