# Generated by Django 3.1.2 on 2021-10-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0085_delete_studentsload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
