# Generated by Django 3.1.2 on 2021-10-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0086_delete_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachersload',
        ),
    ]
