# Generated by Django 3.1.2 on 2021-10-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0087_delete_teachersload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newoffercode',
            old_name='semd_id',
            new_name='sem_id',
        ),
        migrations.AlterUniqueTogether(
            name='newoffercode',
            unique_together={('offer_code', 'sem_id', 'academic_year')},
        ),
    ]
