# Generated by Django 3.1.2 on 2021-10-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0088_auto_20211010_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewStudentsload',
            new_name='Studentsload',
        ),
    ]
