# Generated by Django 3.1.2 on 2021-10-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0091_allstudents_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllStudents',
            new_name='AllStudent',
        ),
    ]
