# Generated by Django 3.1.2 on 2021-10-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0092_auto_20211013_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newoffercode',
            name='id',
        ),
        migrations.AlterField(
            model_name='newoffercode',
            name='offer_code',
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
    ]
