# Generated by Django 3.1.2 on 2021-10-14 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0093_auto_20211014_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfacultyload',
            name='offer_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organization', serialize=False, to='counselling.newoffercode'),
        ),
        migrations.AlterField(
            model_name='studentsload',
            name='offer_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counselling.newoffercode'),
        ),
        migrations.DeleteModel(
            name='OfferCode',
        ),
    ]
