# Generated by Django 3.1.2 on 2021-10-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0095_auto_20211014_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewOfferCode',
            new_name='OfferCode',
        ),
    ]
