# Generated by Django 3.1.2 on 2021-10-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0096_auto_20211014_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllSubjects',
            new_name='AllSubject',
        ),
    ]
