# Generated by Django 3.1.2 on 2021-10-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0098_load'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facultyload',
        ),
    ]
