# Generated by Django 3.1.2 on 2021-10-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0099_delete_facultyload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='load',
            new_name='Facultyload',
        ),
    ]
