# Generated by Django 3.1.2 on 2021-10-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0100_auto_20211014_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('time1', models.TimeField(blank=True, null=True)),
                ('time2', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
