# Generated by Django 3.1.2 on 2021-10-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0101_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselor',
            old_name='employeeid',
            new_name='employee_id',
        ),
    ]
