# Generated by Django 3.1.2 on 2021-10-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0102_auto_20211018_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreated',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
