# Generated by Django 3.1.2 on 2021-11-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0103_auto_20211019_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
