# Generated by Django 3.1.2 on 2021-11-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0104_notification_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='schedule',
            new_name='schedDay',
        ),
        migrations.AddField(
            model_name='notification',
            name='schedTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
