# Generated by Django 3.1.2 on 2021-11-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0106_auto_20211101_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareTime',
            fields=[
                ('id', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('star_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
