# Generated by Django 3.1.2 on 2021-11-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0107_comparetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTime',
            fields=[
                ('id', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('time1', models.TimeField(blank=True, null=True)),
                ('time2', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
