# Generated by Django 3.1.2 on 2021-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0108_newtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersreferral',
            name='feedback',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='teachersreferral',
            name='behavior_problem',
            field=models.CharField(blank=True, choices=[('CHEATING', 'CHEATING'), ('TARDINESS', 'TARDINESS'), ('DISRESPECTFUL', 'DISRESPECTFUL'), ('ATTITUDE', 'ATTITUDE'), ('USING GADGETS IN CLASS', 'USING GADGETS IN CLASS'), ('GRUBBING', 'GRUBBING'), ('OTHERS', 'OTHERS')], max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='teachersreferral',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('DONE', 'DONE')], default=(('PENDING', 'PENDING'), ('DONE', 'DONE')), max_length=220),
        ),
    ]
