# Generated by Django 3.1.2 on 2021-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0109_auto_20211106_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=10000)),
            ],
        ),
    ]
