# Generated by Django 3.1.2 on 2021-11-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0110_counselorfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(blank=True, max_length=220, null=True)),
                ('notification_type', models.CharField(choices=[('automatic_referral', 'automatic_referral'), ('manual_referral', 'manual_referral')], max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('extra_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
    ]
