# Generated by Django 3.1.2 on 2021-11-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0111_notificationfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersreferral',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=220, null=True),
        ),
    ]
