# Generated by Django 3.1.2 on 2021-11-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0112_auto_20211107_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorfeedback',
            name='remarks',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='counselorfeedback',
            name='feedback',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
