# Generated by Django 3.1.2 on 2021-11-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0113_auto_20211112_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSetSched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studnumber', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('lastname', models.CharField(max_length=220)),
                ('degree_program', models.CharField(max_length=220)),
                ('reasons', models.CharField(max_length=10000)),
                ('counselor', models.CharField(max_length=220)),
            ],
        ),
    ]
