# Generated by Django 3.1.2 on 2021-11-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0114_studentsetsched'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsetsched',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsetsched',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsetsched',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
