# Generated by Django 3.1.2 on 2021-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0116_auto_20211119_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, choices=[('1ST SEM', '1ST SEM'), ('2ND SEM', '2ND SEM'), ('SUMMER', 'SUMMER')], max_length=220, null=True)),
                ('school_year', models.CharField(blank=True, choices=[('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022')], max_length=220, null=True)),
            ],
        ),
    ]
