# Generated by Django 3.1.2 on 2021-11-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0117_offering'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepaChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depa_choice', models.CharField(blank=True, choices=[('Department of Language and Literature', 'Department of Language and Literature'), ('Department of Social Sciences and Philosophy', 'Department of Social Sciences and Philosophy'), ('Department of Mathematics and Sciences', 'Department of Mathematics and Sciences'), ('Department of Journalism and Communication', 'Department of Journalism and Communication'), ('Department of Psychology and Library Information Science', 'Department of Psychology and Library Information Science'), ('Department of Accountancy and Finance', 'Department of Accountancy and Finance'), ('Department of Business and Entrepreneurship', 'Department of Business and Entrepreneurship'), ('Department of Marketing and Human Resource Management', 'Department of Marketing and Human Resource Management'), ('Department of Computer Science and Information Technology', 'Department of Computer Science and Information Technology'), ('Student Development and Placement Center', 'Student Development and Placement Center'), ('Center for Religious Education', 'Center for Religious Education'), ('Safety and Security Department', 'Safety and Security Department'), ('Department of Education', 'Department of Education')], max_length=220, null=True)),
            ],
        ),
    ]
