# Generated by Django 3.1.2 on 2021-11-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0119_auto_20211123_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercode',
            name='choice',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='teachersreferral',
            name='choice',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
