# Generated by Django 3.1.2 on 2021-12-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0120_auto_20211124_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_due_date', models.DateField()),
            ],
        ),
    ]
