# Generated by Django 3.1.2 on 2021-12-03 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0121_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
