# Generated by Django 3.1.2 on 2021-12-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0122_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationfeedback',
            name='notification_type',
            field=models.CharField(choices=[('feedback_teacher', 'feedback_teacher'), ('feedback_student', 'feedback_student')], max_length=100),
        ),
    ]
