# Generated by Django 3.1.2 on 2021-12-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0123_auto_20211205_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('automatic_referral', 'automatic_referral'), ('manual_referral', 'manual_referral'), ('appointment', 'appointment')], max_length=100),
        ),
    ]
