# Generated by Django 3.1.2 on 2021-12-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0124_auto_20211206_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllFaculty',
        ),
    ]
