# Generated by Django 3.1.2 on 2021-12-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0125_delete_allfaculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFaculty',
            fields=[
                ('employee_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=220)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.department')),
            ],
        ),
    ]
