# Generated by Django 3.1.2 on 2021-12-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0126_newfaculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyload',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counselling.newfaculty'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
