# Generated by Django 3.1.2 on 2021-12-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0127_auto_20211209_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewFaculty',
            new_name='Faculty',
        ),
    ]
