# Generated by Django 3.1.2 on 2021-12-13 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0129_auto_20211210_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('studnumber', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=220)),
                ('firstname', models.CharField(max_length=220)),
                ('middlename', models.CharField(max_length=220)),
                ('year', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_contact_number', models.CharField(max_length=220)),
                ('address', models.CharField(max_length=220)),
                ('contact_number', models.CharField(max_length=220)),
                ('mother_lastname', models.CharField(max_length=220)),
                ('mother_firstname', models.CharField(max_length=220)),
                ('father_lastname', models.CharField(max_length=220)),
                ('father_firstname', models.CharField(max_length=220)),
                ('parents_contact_number', models.CharField(max_length=220)),
                ('parents_email', models.EmailField(max_length=254)),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.degreeprogram')),
            ],
        ),
    ]
