# Generated by Django 3.1.2 on 2021-12-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0131_studentinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='status',
            field=models.CharField(default='undone', max_length=254),
        ),
    ]
