# Generated by Django 3.1.2 on 2021-12-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0132_auto_20211213_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstudent',
            old_name='email',
            new_name='student_email',
        ),
    ]
