# Generated by Django 3.1.2 on 2021-12-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0134_auto_20211213_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='degree_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.degreeprogram'),
        ),
    ]
