# Generated by Django 3.1.2 on 2022-02-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0136_auto_20220216_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationfeedback',
            name='referral_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
