# Generated by Django 3.1.2 on 2022-02-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0137_notificationfeedback_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='program_designation',
            field=models.CharField(blank=True, choices=[('BSIT', 'BSIT'), ('BSPT', 'BSPT'), ('BSMT', 'BSMT'), ('BSIS', 'BSIS')], max_length=220, null=True),
        ),
    ]
