# Generated by Django 3.1.2 on 2022-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0138_auto_20220217_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='parents_contact_number',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='parents_email',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='father_contact_number',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='guardian_contact_number',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='guardian_firstname',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='guardian_lastname',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='mother_contact_number',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
