# Generated by Django 3.1.2 on 2022-02-22 12:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0139_auto_20220221_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='program_designation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BSIT', 'BSIT'), ('BSIS', 'BSIS'), ('BSCS', 'BSCS'), ('BSA', 'BSA')], max_length=220, null=True),
        ),
    ]
