# Generated by Django 3.1.2 on 2022-02-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0141_holidaytime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='holidaytime',
        ),
    ]
