# Generated by Django 3.1.2 on 2022-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0142_delete_holidaytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='EModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
