# Generated by Django 3.1.2 on 2022-02-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0143_emodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EModel',
        ),
    ]
