# Generated by Django 3.1.2 on 2022-02-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0144_delete_emodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(null=True)),
            ],
        ),
    ]
