# Generated by Django 3.1.2 on 2022-03-29 14:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0145_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickedDate', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.RenameField(
            model_name='degreeprogram',
            old_name='school_id',
            new_name='school_code',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='school_id',
            new_name='school_code',
        ),
        migrations.RemoveField(
            model_name='schooloffices',
            name='school_id',
        ),
        migrations.AlterField(
            model_name='counselor',
            name='program_designation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BSIT', 'BSIT'), ('BSCS', 'BSCS'), ('BSCE', 'BSCE'), ('BSME', 'BSME'), ('BAPOL', 'BAPOL'), ('BSA', 'BSA'), ('BSMA', 'BSMA')], max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='schooloffices',
            name='school_code',
            field=models.CharField(max_length=220, primary_key=True, serialize=False),
        ),
    ]
