# Generated by Django 3.1.2 on 2022-03-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0146_auto_20220329_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDepartment',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=220)),
                ('school_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.schooloffices')),
            ],
        ),
    ]
