# Generated by Django 3.1.2 on 2022-03-19 02:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0147_auto_20220224_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor',
            name='program_designation',
        ),
        migrations.RemoveField(
            model_name='counselor',
            name='school_choice',
        ),
        migrations.AddField(
            model_name='counselor',
            name='proram_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BSIT', 'BSIT'), ('BSCS', 'BSCS'), ('BSCE', 'BSCE'), ('BSME', 'BSME'), ('BAPOL', 'BAPOL'), ('BSA', 'BSA'), ('BSMA', 'BSMA')], max_length=220, null=True),
        ),
    ]
