# Generated by Django 3.1.2 on 2022-03-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0148_auto_20220319_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselor',
            old_name='proram_choice',
            new_name='program_designation',
        ),
    ]
