# Generated by Django 3.1.2 on 2022-03-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0149_auto_20220319_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degreeprogram',
            old_name='school_id',
            new_name='school_code',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='school_id',
            new_name='school_code',
        ),
        migrations.RemoveField(
            model_name='schooloffices',
            name='school_id',
        ),
        migrations.AlterField(
            model_name='schooloffices',
            name='school_code',
            field=models.CharField(max_length=220, primary_key=True, serialize=False),
        ),
    ]
