# Generated by Django 3.1.2 on 2022-04-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0151_auto_20220402_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsubject',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.newdepartment'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
