# Generated by Django 3.1.2 on 2022-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0152_auto_20220402_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdepartment',
            name='department_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
