# Generated by Django 3.1.2 on 2022-04-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0153_auto_20220402_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=220)),
            ],
        ),
    ]
