# Generated by Django 3.1.2 on 2022-04-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0154_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
