# Generated by Django 3.1.2 on 2022-04-05 14:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0157_auto_20220405_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersreferral',
            name='behavior_problem',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHEATING', 'CHEATING'), ('TARDINESS', 'TARDINESS'), ('DISRESPECTFUL', 'DISRESPECTFUL'), ('ATTITUDE', 'ATTITUDE'), ('USING GADGETS IN CLASS', 'USING GADGETS IN CLASS'), ('GRUBBING', 'GRUBBING'), ('OTHERS', 'OTHERS')], max_length=220, null=True),
        ),
    ]
