# Generated by Django 3.1.2 on 2022-04-06 16:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0159_auto_20220407_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='program_designation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BSIT', 'BSIT'), ('BSCS', 'BSCS'), ('BSCE', 'BSCE'), ('BSIS', 'BSIS'), ('BAPOL', 'BAPOL'), ('BSA', 'BSA'), ('BSMA', 'BSMA')], max_length=220, null=True),
        ),
    ]
