# Generated by Django 3.1.2 on 2022-04-06 17:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0160_auto_20220407_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='program_designation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['BSIT', 'BSIT'], ['BSCS', 'BSCS'], ['BSIS', 'BSIS'], ['BSEMC', 'BSEMC'], ['BSEDSCI', 'BSEDSCI'], ['BSEDENG', 'BSEDENG'], ['BSEDMATH', 'BSEDMATH'], ['BSEDFIL', 'BSEDFIL'], ['BPED', 'BPED'], ['BEEDGEN', 'BEEDGEN'], ['BEEDECE', 'BEEDECE'], ['BSNED', 'BSNED'], ['BSCE', 'BSCE'], ['BSME', 'BSME'], ['BSCPE', 'BSCPE'], ['BSEE', 'BSEE'], ['BSECE', 'BSECE'], ['BSPSYCH', 'BSPSYCH'], ['BSLIBSCI', 'BSLIBSCI'], ['BSBIOMED', 'BSBIOMED'], ['BSBIOMICRO', 'BSBIOMICRO'], ['BSCOMM', 'BSCOMM'], ['BSMARCOMM', 'BSMARCOMM'], ['BSIS', 'BSIS'], ['ABPOLSCI', 'ABPOLSCI'], ['ABELS', 'ABELS'], ['BSA', 'BSA'], ['BSMGT', 'BSMGT'], ['BSBAFIN', 'BSBAFIN'], ['BSBAOM', 'BSBAOM'], ['BSBAHRM', 'BSBAHRM'], ['BSTM', 'BSTM'], ['BSHM', 'BSHM'], ['BSHMFB', 'BSHMFB']], max_length=220, null=True),
        ),
    ]
