# Generated by Django 3.1.2 on 2022-04-14 06:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0161_auto_20220407_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='program_designation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['BSIT', 'BSIT'], ['BSCS', 'BSCS'], ['BSIS', 'BSIS'], ['BSEMC', 'BSEMC'], ['BSEDSCI', 'BSEDSCI'], ['BSEDENG', 'BSEDENG'], ['BSEDMATH', 'BSEDMATH'], ['BSEDFIL', 'BSEDFIL'], ['BPED', 'BPED'], ['BEEDGEN', 'BEEDGEN'], ['BEEDECE', 'BEEDECE'], ['BSNED', 'BSNED'], ['BSCE', 'BSCE'], ['BSME', 'BSME'], ['BSCPE', 'BSCPE'], ['BSEE', 'BSEE'], ['BSECE', 'BSECE'], ['BSPSYCH', 'BSPSYCH'], ['BSLIBSCI', 'BSLIBSCI'], ['BSBIOMED', 'BSBIOMED'], ['BSBIOMICRO', 'BSBIOMICRO'], ['BSCOMM', 'BSCOMM'], ['BSMARCOMM', 'BSMARCOMM'], ['ABPOLSCI', 'ABPOLSCI'], ['ABELS', 'ABELS'], ['BSA', 'BSA'], ['BSMGT', 'BSMGT'], ['BSBAFIN', 'BSBAFIN'], ['BSBAOM', 'BSBAOM'], ['BSBAHRM', 'BSBAHRM'], ['BSTM', 'BSTM'], ['BSHM', 'BSHM'], ['BSHMFB', 'BSHMFB']], max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='depachoice',
            name='depa_choice',
            field=models.CharField(choices=[['Department of Language and Literature', 'Department of Language and Literature'], ['Department of Social Sciences and Philosophy', 'Department of Social Sciences and Philosophy'], ['Department of Mathematics and Sciences', 'Department of Mathematics and Sciences'], ['Department of Journalism and Communication', 'Department of Journalism and Communication'], ['Department of Psychology and Library Information Science', 'Department of Psychology and Library Information Science'], ['Department of Accountancy and Finance', 'Department of Accountancy and Finance'], ['Department of Business and Entrepreneurship', 'Department of Business and Entrepreneurship'], ['Department of Marketing and Human Resource Management', 'Department of Marketing and Human Resource Management'], ['Department of Computer Science and Information Technology', 'Department of Computer Science and Information Technology'], ['Student Development and Placement Center', 'Student Development and Placement Center'], ['Center for Religious Education', 'Center for Religious Education'], ['Safety and Security Department', 'Safety and Security Department'], ['Department of Education', 'Department of Education']], max_length=220),
        ),
    ]
