# Generated by Django 3.1.2 on 2022-04-14 07:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0162_auto_20220414_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersreferral',
            name='behavior_problem',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHEATING', 'CHEATING'), ('TARDINESS', 'TARDINESS'), ('DISRESPECTFUL', 'DISRESPECTFUL'), ('BAD ATTITUDE', 'BAD ATTITUDE'), ('OTHERS', 'OTHERS')], max_length=220, null=True),
        ),
    ]
