# Generated by Django 3.1.2 on 2022-04-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0163_auto_20220414_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectwithsem',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.subject'),
        ),
        migrations.DeleteModel(
            name='AllSubject',
        ),
    ]
