# Generated by Django 3.1.2 on 2022-04-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0164_auto_20220414_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTable',
        ),
    ]
