# Generated by Django 3.1.2 on 2022-04-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0166_setschedulecounselor'),
    ]

    operations = [
        migrations.AddField(
            model_name='setschedulecounselor',
            name='employee_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='setschedulecounselor',
            name='pickedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
