# Generated by Django 3.1.2 on 2022-05-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0167_auto_20220415_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='setschedulecounselor',
            name='choice',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
