# Generated by Django 3.1.2 on 2022-05-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0168_setschedulecounselor_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setschedulecounselor',
            old_name='pickedDate',
            new_name='date',
        ),
    ]
