# Generated by Django 3.1.2 on 2022-04-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0170_offering_depa_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepaChoice',
        ),
    ]
