# Generated by Django 3.1.2 on 2022-04-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0172_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTime',
            fields=[
                ('time_id', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('time1', models.TimeField()),
                ('time2', models.TimeField()),
            ],
        ),
    ]
