# Generated by Django 3.1.2 on 2022-04-30 16:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0174_delete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='program_designation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['BSIT', 'Bachelor of Science in Information Technology'], ['BSCS', 'Bachelor of Science in Computer Science'], ['BSIS', 'Bachelor of Science in Information System'], ['BSEMC', 'Bachelor of Science in Entertainment and Multimedia Computing'], ['BSEDSCI', 'Bachelor of  Secondary Education Major in Science'], ['BSEDENG', 'Bachelor of  Secondary Education Major in English'], ['BSEDMATH', 'Bachelor of  Secondary Education Major in Math'], ['BSEDFIL', 'Bachelor of Science in Secondary Education Major in Filipino'], ['BPED', 'Bachelor of Sciecne in Physical Education'], ['BEEDGEN', 'Bachelor of Elementary Education Generalist'], ['BEEDECE', 'Bachelor of Elementary Education major in Early Childhood Education'], ['BSNED', 'Bachelor of Special Needs Education'], ['BSCE', 'Bachelor of Science in Civil Engineering'], ['BSME', 'Bachelor of Science in Mechanical Engineering'], ['BSCPE', 'Bachelor of Science in Computer Engineering'], ['BSEE', 'Bachelor of Science in Electrical Engineering'], ['BSECE', 'Bachelor of Science in Electronics and Communication Engineering'], ['BSPSYCH', 'Bachelor of Science in Psychology'], ['BSLIBSCI', 'Bachelor of Science in  Library Science'], ['BSBIOMED', 'Bachelor of Science in Biology Major in Medical Biology'], ['BSBIOMICRO', 'Bachelor of Science in Biology Major in Microbiology'], ['BSCOMM', 'Bachelor of Science in Communication'], ['BSMARCOMM', 'Bachelor of Science in Marketing Communication'], ['ABPOLSCI', 'Bachelor of Arts in Political Science'], ['ABELS', 'Bachelor of Arts in English Language Studies'], ['BSA', 'Bachelor of Science in Accountancy'], ['BSMGT', 'Bachelor of Science  in Management Accounting'], ['BSBAFIN', 'Bachelor of Science in Business Administration Major in Financial Management'], ['BSBAOM', 'Bachelor of Science in Business Administration Major in Operations  Management'], ['BSBAHRM', 'Bachelor of Science in Business Administration Major in Human Resource Management'], ['BSTM', 'Bachelor of Science in Tourism Management'], ['BSHM', 'Bachelor of Science in Hospitality Management'], ['BSHMFB', 'Bachelor of Science in Hospitality Management Major in Food and Beverage']], max_length=220, null=True),
        ),
    ]
