# Generated by Django 3.1.2 on 2022-04-30 16:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0175_auto_20220501_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='program_designation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['BSIT', 'BSIT - Bachelor of Science in Information Technology'], ['BSCS', 'BSCS - Bachelor of Science in Computer Science'], ['BSIS', 'BSIS - Bachelor of Science in Information System'], ['BSEMC', 'BSEMC - Bachelor of Science in Entertainment and Multimedia Computing'], ['BSEDSCI', 'BSEDSCI - Bachelor of  Secondary Education Major in Science'], ['BSEDENG', 'BSEDENG - Bachelor of  Secondary Education Major in English'], ['BSEDMATH', 'BSEDMATH - Bachelor of  Secondary Education Major in Math'], ['BSEDFIL', 'BSEDFIL - Bachelor of Science in Secondary Education Major in Filipino'], ['BPED', 'BPED - Bachelor of Sciecne in Physical Education'], ['BEEDGEN', 'BEEDGEN - Bachelor of Elementary Education Generalist'], ['BEEDECE', 'BEEDECE - Bachelor of Elementary Education major in Early Childhood Education'], ['BSNED', 'BSNED - Bachelor of Special Needs Education'], ['BSCE', 'BSCE - Bachelor of Science in Civil Engineering'], ['BSME', 'BSME - Bachelor of Science in Mechanical Engineering'], ['BSCPE', 'BSCPE - Bachelor of Science in Computer Engineering'], ['BSEE', 'BSEE - Bachelor of Science in Electrical Engineering'], ['BSECE', 'BSECE - Bachelor of Science in Electronics and Communication Engineering'], ['BSPSYCH', 'BSPSYCH - Bachelor of Science in Psychology'], ['BSLIBSCI', 'BSLIBSCI - Bachelor of Science in  Library Science'], ['BSBIOMED', 'BSBIOMED - Bachelor of Science in Biology Major in Medical Biology'], ['BSBIOMICRO', 'BSBIOMICRO - Bachelor of Science in Biology Major in Microbiology'], ['BSCOMM', 'BSCOMM - Bachelor of Science in Communication'], ['BSMARCOMM', 'BSMARCOMM - Bachelor of Science in Marketing Communication'], ['ABPOLSCI', 'ABPOLSCI - Bachelor of Arts in Political Science'], ['ABELS', 'ABELS - Bachelor of Arts in English Language Studies'], ['BSA', 'BSA - Bachelor of Science in Accountancy'], ['BSMGT', 'BSMGT - Bachelor of Science  in Management Accounting'], ['BSBAFIN', 'BSBAFIN - Bachelor of Science in Business Administration Major in Financial Management'], ['BSBAOM', 'BSBAOM - Bachelor of Science in Business Administration Major in Operations  Management'], ['BSBAHRM', 'BSBAHRM - Bachelor of Science in Business Administration Major in Human Resource Management'], ['BSTM', 'BSTM - Bachelor of Science in Tourism Management'], ['BSHM', 'BSHM - Bachelor of Science in Hospitality Management'], ['BSHMFB', 'BSHMFB - Bachelor of Science in Hospitality Management Major in Food and Beverage']], max_length=220, null=True),
        ),
    ]
