# Generated by Django 3.1.2 on 2022-06-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0176_auto_20220501_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
