# Generated by Django 3.1.2 on 2022-06-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0177_filterdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterdate',
            old_name='end_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='filterdate',
            old_name='start_date',
            new_name='to_date',
        ),
    ]
