# Generated by Django 3.1.2 on 2022-06-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0178_auto_20220604_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterDate',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='pickedDate',
            new_name='pickedEndDate',
        ),
        migrations.AddField(
            model_name='calendar',
            name='pickedStartDate',
            field=models.DateField(null=True),
        ),
    ]
