# Generated by Django 3.1.2 on 2022-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0179_auto_20220604_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickedStartDate', models.DateField(null=True)),
                ('pickedEndDate', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='pickedEndDate',
            new_name='pickedDate',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='pickedStartDate',
        ),
    ]
