# Generated by Django 3.1.2 on 2022-06-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0180_auto_20220604_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Calendar'},
        ),
    ]
