# Generated by Django 3.1.2 on 2022-06-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0181_auto_20220606_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name_plural': 'Calendar'},
        ),
    ]
