# Generated by Django 3.1.2 on 2022-06-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0182_auto_20220606_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterdate',
            options={'verbose_name_plural': 'FilterDate'},
        ),
        migrations.AlterModelOptions(
            name='newtime',
            options={'verbose_name_plural': 'NewTime'},
        ),
        migrations.AlterModelOptions(
            name='setschedulecounselor',
            options={'verbose_name_plural': 'SetScheduleCounselor'},
        ),
    ]
