# Generated by Django 3.1.2 on 2022-06-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0183_auto_20220606_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcreated',
            options={'verbose_name_plural': 'AccountCreated'},
        ),
        migrations.AlterModelOptions(
            name='accountsapi',
            options={'verbose_name_plural': 'AccountsApi'},
        ),
        migrations.AlterModelOptions(
            name='allstudent',
            options={'verbose_name_plural': 'AllStudent'},
        ),
        migrations.AlterModelOptions(
            name='counselor',
            options={'verbose_name_plural': 'Counselor'},
        ),
        migrations.AlterModelOptions(
            name='counselorfeedback',
            options={'verbose_name_plural': 'CounselorFeedback'},
        ),
        migrations.AlterModelOptions(
            name='degreeprogram',
            options={'verbose_name_plural': 'DegreeProgram'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty'},
        ),
        migrations.AlterModelOptions(
            name='facultyload',
            options={'verbose_name_plural': 'Facultyload'},
        ),
        migrations.AlterModelOptions(
            name='newdepartment',
            options={'verbose_name_plural': 'NewDepartment'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Notification'},
        ),
        migrations.AlterModelOptions(
            name='notificationfeedback',
            options={'verbose_name_plural': 'NotificationFeedback'},
        ),
        migrations.AlterModelOptions(
            name='offercode',
            options={'verbose_name_plural': 'Offering'},
        ),
        migrations.AlterModelOptions(
            name='offering',
            options={'verbose_name_plural': 'Offering'},
        ),
        migrations.AlterModelOptions(
            name='schooloffices',
            options={'verbose_name_plural': 'SchoolOffices'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': 'Semester'},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name_plural': 'StudentInfo'},
        ),
        migrations.AlterModelOptions(
            name='studentsetsched',
            options={'verbose_name_plural': 'StudentSetSched'},
        ),
        migrations.AlterModelOptions(
            name='studentsload',
            options={'verbose_name_plural': 'Studentsload'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subject'},
        ),
        migrations.AlterModelOptions(
            name='subjectoffered',
            options={'verbose_name_plural': 'SubjectOffered'},
        ),
        migrations.AlterModelOptions(
            name='subjectwithsem',
            options={'verbose_name_plural': 'SubjectWithSem'},
        ),
        migrations.AlterModelOptions(
            name='teachersreferral',
            options={'verbose_name_plural': 'TeachersReferral'},
        ),
    ]
